[[colors.indexed_colors]]
color = "#fab387"
index = 16

[[colors.indexed_colors]]
color = "#f5e0dc"
index = 17

[colors.bright]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.dim]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.footer_bar]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.end]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.start]
background = "#f9e2af"
foreground = "#1e1e2e"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
bright_foreground = "#cdd6f4"
dim_foreground = "#7f849c"
foreground = "#cdd6f4"

[colors.search.focused_match]
background = "#a6e3a1"
foreground = "#1e1e2e"

[colors.search.matches]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[cursor]
style = "Block"
vi_mode_style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 19

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.glyph_offset]
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
y = 0

[scrolling]
history = 1000
multiplier = 3

[window]
decorations = "none"
opacity = 0.7

[window.dimensions]
columns = 80
lines = 35

[window.padding]
x = 5
y = 5
